### ISSUE TITLE
Check procedure

### ISSUE THREAD

**Issue by niccoX** [javicacheiro/check_smart#1]
```
for disk in $DISKS; do
    RESULT=$(smartctl -H /dev/$disk | parse | verify)
    if [[ -n $RESULT ]]; then
        FAILURES+=$disk
        ERRORS=1
```
The `smartctl` command, if not being executed correctly it doesn't give an output.
I need to run `smartctl` with distinct flags to get a SMART status:

`smartctl -H /dev/vda -d scsi -T permissive`

So with the script I can't really test that `smartctl -H /dev/$disk | parse | verify`will work, as it doesn't take it into account. It will display OK without any commands being run.

**Comment by javicacheiro** [comment]
Please test the new version to see if it solves your issues:
- There is now a variable OPT at the begining of the file where you can add the "-d scsi" default option.
- Better error handling: if smartctl fails then it sets the status as warning for that disk

**Comment by niccoX** [comment]
I end up getting a `WARNING: vda`with and without the `-d scsi` option. I even added a new `$OPTS2="-T permissive"`.

`OUTPUT=$(smartctl -H /dev/$disk $OPTS $OPTS2)`

This is the output of `smartctl -H /dev/vda -d scsi -T permissive`

```
Short INQUIRY response, skip product id
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
```

**Comment by niccoX** [comment]
The script works for a disk that is not requiring any additional flags, we tested with a normal disk and one with SMART errors.

But the 3rd disk that requires `-d scsi` and `-T permissive`, I'll always end up with a `Warning: vda`

I have added two variables:

```
OPTS="-d scsi"
OPTS2="-T permissive"
```

`OUTPUT=$(smartctl -H /dev/$disk $OPTS $OPTS2)`

I did it manually as well:

`(smartctl -H /dev/$disk -d scsi -T permissive)`

**Comment by javicacheiro** [comment]
I have added support for the new format. Please test the new version to confirm if it fixes the issue.

It seems that the smartctl version in your system reports in a slightly different way. Which Linux distribution and smartcl version are you using?

**Comment by javicacheiro** [comment]
Just another comment, about the OPTS there is no need to use two variables just write everything under OPTS like:
OPTS="-d scsi -T permissive"

**Comment by javicacheiro** [comment]
Keep in mind that with the new version when you have a WARNING it means that the smartctl command failed to execute.

**Comment by niccoX** [comment]
I use:

Ubuntu 18.04.1 LTS

And compiled `smartmontools`, on the server that doesn't work, `Warning: vda`, with the OK SMART disk that requires options. The other instance we tested, two disks one faulty disk other OK both don't require options and tested with a Mac, smartmontools installed with `brew`. And manually added `DISKS=` since `lsbkl` is not a command in the Mac.

**Comment by niccoX** [comment]
> I have added support for the new format. Please test the new version to confirm if it fixes the issue.
> 
> It seems that the smartctl version in your system reports in a slightly different way. Which Linux distribution and smartcl version are you using?

I don't know, if I run the command in the shell it works, and same command for both versions of _smartmontools_ I have installed.

**Comment by niccoX** [comment]
Just tested, I still end up with `WARNING: vda`.

**Comment by niccoX** [comment]
Filesystem      Size  Used Avail Use% Mounted on
udev            481M     0  481M   0% /dev
tmpfs            99M  628K   98M   1% /run
/dev/vda1        25G  4.2G   20G  18% /
tmpfs           493M     0  493M   0% /sys/fs/cgroup
tmpfs            99M     0   99M   0% /run/user/0

**Comment by niccoX** [comment]
```
lsblk -nio KNAME,TYPE | grep disk | awk '{print $1}'
vda
```
```
smartctl -d scsi -T permissive -H /dev/vda
smartctl 6.6 2017-11-05 r4594 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
```
```
./check_smartmon2
WARNING: vda
```

**Comment by niccoX** [comment]
> Keep in mind that with the new version when you have a WARNING it means that the smartctl command failed to execute.

Must be an error in the code, because as you can see that command will execute in the shell.

**Comment by niccoX** [comment]
I don't think these outputs matter, but will list them:

**vda**

```
smartctl --scan
# scan_smart_devices: glob(3) aborted matching pattern /dev/discs/disc*
```

```
smartctl -d scsi -T permissive --all /dev/vda -H
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Read defect list: asked for grown list but didn't get it
Error Counter logging not supported

Device does not support Self Test logging
```

**disk1** (Mac disk)

```
smartctl --scan
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SATA@1F,2/AppleIntelPchSeriesAHCI/PRT0@0/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice -d ata # IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SATA@1F,2/AppleIntelPchSeriesAHCI/PRT0@0/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice, ATA device
```

**Comment by niccoX** [comment]
It might be the difference of the output:

**disk1**

```
smartctl -H /dev/disk1
smartctl 6.6 2017-11-05 r4594 [Darwin 17.7.0 x86_64] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
```

**vda** (PS: I unistalled the compiled and installed through apt...)

```
smartctl -d scsi -T permissive -H /dev/vda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
```

```
verify() {
    egrep -v '(SMART overall-health self-assessment test result: PASSED|SMART STATUS RETURN: incomplete response, ATA output registers missing|SMART Health Status: OK)'
}
```

Could that extra line: `Short INQUIRY response, skip product id` be the trouble?

**Comment by niccoX** [comment]
Noticed some weird behavior. I got the script to execute correctly two times with the OK status. I catched the output.

This must have happened because the output was without the `Short INQUIRY response, skip product id`. And sure it must have. I ran `smartctl -d scsi -T permissive -H /dev/vda`maybe 50 times in a row, and one time it did execute without the `Short INQUIRY response, skip product id`, which must have happened as well those two times when the script gave correct status. I don't know why the command sometimes skips it, doesn't happen to often though. But it's definitely this line that is causing the issue on the **vda** machine.

**This is the normal behavior, and conflict with the script:**

```
smartctl -d scsi -T permissive -H /dev/vda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
```
**When the script executed correctly:**

```
root@tls13:/usr/lib/nagios/plugins# ./check_smartmon2
OK
```

**This is the occasion when that line was not in the output, and the reason the script worked:**

```
smartctl -d scsi -T permissive -H /dev/vda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK
```
There might be different ways you can address this in the script so it workes with 2-3 lines or maybe even more lines, I don't know if some instances can generate more info than 2-3 lines.

**Comment by niccoX** [comment]
Changing this to 3 lines didn't solve it for me:

`if [[ $LINES == 3 ]]; then`

**Comment by javicacheiro** [comment]
Looking at the behaviour I think the problem is in the exit code returned by smartctl.

Could you check what is the exit code when you get the "Short INQUIRY response, skip product id" and in the other case?

To check it run the following command just after running smartctl:
```
echo $?
```

**Comment by niccoX** [comment]
I'm testing now on the **vda** that doesn't have any SMART errors. As previously stated, I can run the script 30 times, 28 times it will generate the bug "WARNING: vda" and two times it will be fine "OK". I captured the exit status for both executions:

```
root@tls13:/usr/lib/nagios/plugins# ./check_smartmon
OK
root@tls13:/usr/lib/nagios/plugins# echo $?
0

root@tls13:/usr/lib/nagios/plugins# ./check_smartmon
WARNING: vda
root@tls13:/usr/lib/nagios/plugins# echo $?
1
```

**Comment by niccoX** [comment]
So if the line is generated it will end up with exit status 1 with the script and exit status 2 with the command, which will give out the warning. If you can adapt the script and improve that.

```
root@tls13:/usr/lib/nagios/plugins# smartctl -d scsi -T permissive -H /dev/vda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Short INQUIRY response, skip product id
=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

root@tls13:/usr/lib/nagios/plugins# echo $?
2
```

```
root@tls13:/usr/lib/nagios/plugins# smartctl -d scsi -T permissive -H /dev/vda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-30-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

root@tls13:/usr/lib/nagios/plugins# echo $?
0
```

**Comment by javicacheiro** [comment]
The behaviour is correct because with the patch:
- If smartctl fails then it sets the status as warning for that disk

If smartctl runs correctly it will give exit status 0, in other cases it means smartctl encountered some issue while executing. In a generic solution I think it is better to flag this situation as a WARNING.

If we do not do it this way and only verify the "SMART Health Status: OK" text, then it could be that the command is reporting some issue and it will be ignored.

It is really surprising that in the VM smartctl 2 of 30 times run correctly (exit status 0) and the other 28 it finds issues with the short inquiry (exit status 2). I think the runs with the exit status 2 are really the ones we would like to fix. 

You can try the "verypermissive" option and see if that makes smartctl to return with exit status 0. In any case keep in mind that permissive and verypermissive are actually options that tell smartctl to ignore failures of mandatory SMART commands:


```
permissive - ignore failure(s) of mandatory SMART commands.  This option may be given more than once.  Each  addi‐
tional  use of this option will cause one more additional failure to be ignored.  Note that the use of this option
can lead to messages like "Feature X not supported", followed shortly by "Feature X enable failed".  In a few such
cases, contrary to the final message, Feature X is enabled.

verypermissive  - equivalent to giving a large number of ´-T permissive´ options: ignore failures of any number of
mandatory SMART commands.  Please see the note above.
```

**Comment by niccoX** [comment]
I'll try that option. I need to use that option for smartctl to run on this particular drive, I don't have any other solution.

I'll check how nagios is responding as a message to exit status 2, don't remember at the moment.

**Comment by javicacheiro** [comment]
Nagios uses the exit status to provide the status of the service:
- 0: OK
- 1: WARNING
- 2: CRITICAL
